name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["latest"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics 1
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.SUMMARY_CARDS_TOKEN }}

          # Options
          filename: metrics1.svg
          user: Kashiwade-music
          base: header, activity, repositories, metadata
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_analysis_timeout: 30
          plugin_languages_recent_days: 365
          plugin_languages_aliases: TSX:typescript
          commits_authoring: Kashiwade-music, ${{ secrets.EMAIL }}, kashiwade, Kashiwade

      - name: Metrics 2
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.SUMMARY_CARDS_TOKEN }}

          # Options
          filename: metrics2.svg
          user: Kashiwade-music
          base: ""
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          plugin_stars: yes
          plugin_stars_limit: 3
