name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Metrics 1
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.SUMMARY_CARDS_TOKEN }}

          # Options
          filename: metrics1.svg
          user: Kashiwade-music
          base: header, activity, repositories, metadata
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            less, dockerfile, makefile, qmake, lex, cmake,
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_analysis_timeout: 15
          use_prebuilt_image: yes

      - name: Metrics 2
        uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.SUMMARY_CARDS_TOKEN }}

          # Options
          filename: metrics2.svg
          user: Kashiwade-music
          base: ""
          config_timezone: Asia/Tokyo
          config_twemoji: yes
          plugin_stars: yes
          plugin_stars_limit: 3
          use_prebuilt_image: yes
